# This email contains the common information for all applications

# Logging config
logging.level:
  com.netflix.discovery: 'INFO'

# Eureka - Service Discovery
eureka.instance:
  prefer-ip-address: true

# Spring config
spring.jackson:
  serialization:
    indent_output: true

# Security config
security.oauth2.resource:
  user-info-uri: http://security/me
  load-balanced: true
